# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 18:21
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True)),
                ('dob', models.DateField()),
                ('address', models.CharField(default='The person has not specified their address yet', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('resume_url', models.CharField(max_length=100, null=True)),
                ('user_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('title', models.CharField(choices=[('Architectural and Engineering Managers', 'Architectural and Engineering Managers'), ('Auditors', 'Auditors'), ('Business Intelligence Analysts', 'Business Intelligence Analysts'), ('Business Teachers, Postsecondary', 'Business Teachers, Postsecondary'), ('Computer and Information Research Scientists', 'Computer and Information Research Scientists'), ('Computer and Information Systems Managers', 'Computer and Information Systems Managers'), ('Computer Hardware Engineers', 'Computer Hardware Engineers'), ('Computer Network Architects', 'Computer Network Architects'), ('Computer Network Support Specialists', 'Computer Network Support Specialists'), ('Computer Numerically Controlled Machine Tool Programmers, Metal and Plastic', 'Computer Numerically Controlled Machine Tool Programmers, Metal and Plastic'), ('Computer Programmers', 'Computer Programmers'), ('Computer Science Teachers, Postsecondary', 'Computer Science Teachers, Postsecondary'), ('Computer Systems Analysts', 'Computer Systems Analysts'), ('Computer User Support Specialists', 'Computer User Support Specialists'), ('Database Administrators', 'Database Administrators'), ('Electrical Engineering Technicians', 'Electrical Engineering Technicians'), ('Electronics Engineering Technicians', 'Electronics Engineering Technicians'), ('Engineering Teachers, Postsecondary', 'Engineering Teachers, Postsecondary'), ('Financial Quantitative Analysts', 'Financial Quantitative Analysts'), ('Graphic Designers', 'Graphic Designers'), ('Information Security Analysts', 'Information Security Analysts'), ('Mechatronics Engineers', 'Mechatronics Engineers'), ('Natural Sciences Managers', 'Natural Sciences Managers'), ('Operations Research Analysts', 'Operations Research Analysts'), ('Security Management Specialists', 'Security Management Specialists'), ('Software Developers, Applications', 'Software Developers, Applications'), ('Software Developers, Systems Software', 'Software Developers, Systems Software'), ('Telecommunications Engineering Specialists', 'Telecommunications Engineering Specialists'), ('Video Game Designers', 'Video Game Designers')], default='', max_length=100)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('date_published', models.DateField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='personorganization',
            name='skills',
            field=models.ManyToManyField(to='mainapp.Skill'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='skills',
            field=models.ManyToManyField(to='mainapp.Skill'),
        ),
        migrations.AlterUniqueTogether(
            name='personorganization',
            unique_together=set([('person', 'organization', 'title')]),
        ),
    ]
