# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_personorganization_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='skills',
            field=models.ManyToManyField(null=True, to='mainapp.Skill'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Personal'),
        ),
    ]
