# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20160411_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('A', 'Applied'), ('S', 'Selected'), ('X', 'Shortlisted'), ('R', 'Rejected')], default='A', max_length=1)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Personal')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.JobPosting')),
            ],
        ),
    ]
