# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='score',
            field=models.IntegerField(),
        ),
    ]
