# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20160412_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
