# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20160412_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 4, 12, 12, 24, 37, 269809, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
