# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_jobapplication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('optionA', models.CharField(max_length=200)),
                ('optionB', models.CharField(max_length=200)),
                ('optionC', models.CharField(max_length=200)),
                ('optionD', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Skill')),
            ],
        ),
    ]
